# Generated by Django 4.1.2 on 2022-11-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=3, verbose_name='Customer ID')),
                ('cust_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('cust_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('cust_dob', models.DateField(verbose_name="Customer's Date of Birth")),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=3, verbose_name='Employee ID')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('emp_pay_rate', models.CharField(max_length=6, verbose_name='Pay Rate')),
                ('emp_weekly_hours', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Weekly Hours')),
                ('emp_start_date', models.DateField(verbose_name='Employee Start Date')),
                ('emp_dob', models.DateField(verbose_name='Date of Birth')),
                ('emp_email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
        ),
    ]
