# Generated by Django 4.1.2 on 2022-11-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posapp', '0002_showitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='showItems',
        ),
    ]
